// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Web app not configured yet
  // To configure web:
  // 1. Go to https://console.firebase.google.com/project/walkmypet-47e03/settings/general
  // 2. Click the Web icon (</>) to add a web app
  // 3. Register the app and copy the appId
  // 4. Update the appId below
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY3MWESY1wvWjzAOCaHaAO0h8WOQRFk9s',
    appId: '1:885639863246:web:PLACEHOLDER_UPDATE_THIS',
    messagingSenderId: '885639863246',
    projectId: 'walkmypet-47e03',
    authDomain: 'walkmypet-47e03.firebaseapp.com',
    storageBucket: 'walkmypet-47e03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY3MWESY1wvWjzAOCaHaAO0h8WOQRFk9s',
    appId: '1:885639863246:android:dbac8511ae6a1c1acae99f',
    messagingSenderId: '885639863246',
    projectId: 'walkmypet-47e03',
    storageBucket: 'walkmypet-47e03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVTyfJWG_tLqpS4pRxo4_QGc49tAsL4g',
    appId: '1:885639863246:ios:08b8208286a76d56cae99f',
    messagingSenderId: '885639863246',
    projectId: 'walkmypet-47e03',
    storageBucket: 'walkmypet-47e03.firebasestorage.app',
    iosBundleId: 'com.WalkMyPet.walkmypet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.walkmypet.myapp',
  );
}