// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGR7OrLSL1yW47Ep7jzg5T5Ex7lBfuzCI',
    appId: '1:830819672498:web:9a0cb1438c889ac64c04ab',
    messagingSenderId: '830819672498',
    projectId: 'walkmypet-dff4e',
    authDomain: 'walkmypet-dff4e.firebaseapp.com',
    storageBucket: 'walkmypet-dff4e.firebasestorage.app',
    measurementId: 'G-G66C0KFLDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAuAH15j5txXTqccjKOoBTYvi3E5i4bIQ',
    appId: '1:830819672498:android:ab70ae04eb47954b4c04ab',
    messagingSenderId: '830819672498',
    projectId: 'walkmypet-dff4e',
    storageBucket: 'walkmypet-dff4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBouinu6HhkApZsR3jCqH2usQ1OJRhDBAU',
    appId: '1:830819672498:ios:3e383d2b787750264c04ab',
    messagingSenderId: '830819672498',
    projectId: 'walkmypet-dff4e',
    storageBucket: 'walkmypet-dff4e.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
