// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_sOOeYw3o482d0a7XXsXam9biGjq0AEU',
    appId: '1:885639863246:web:417604ee1cb499cacae99f',
    messagingSenderId: '885639863246',
    projectId: 'walkmypet-47e03',
    authDomain: 'walkmypet-47e03.firebaseapp.com',
    storageBucket: 'walkmypet-47e03.firebasestorage.app',
    measurementId: 'G-EHJRR5G7DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY3MWESY1wvWjzAOCaHaAO0h8WOQRFk9s',
    appId: '1:885639863246:android:dbac8511ae6a1c1acae99f',
    messagingSenderId: '885639863246',
    projectId: 'walkmypet-47e03',
    storageBucket: 'walkmypet-47e03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVTyfJWG_tLqpS4pRxo4_QGc49tAsL4g',
    appId: '1:885639863246:ios:066f1c1233883517cae99f',
    messagingSenderId: '885639863246',
    projectId: 'walkmypet-47e03',
    storageBucket: 'walkmypet-47e03.firebasestorage.app',
    iosClientId: '885639863246-mqpmrq9j0ulgd0511tmp64ma1id9peck.apps.googleusercontent.com',
    iosBundleId: 'com.walkmypet.walkmypet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUVTyfJWG_tLqpS4pRxo4_QGc49tAsL4g',
    appId: '1:885639863246:ios:08b8208286a76d56cae99f',
    messagingSenderId: '885639863246',
    projectId: 'walkmypet-47e03',
    storageBucket: 'walkmypet-47e03.firebasestorage.app',
    iosClientId: '885639863246-o64nhevffrnvhcj103ffhtf1vcikq30j.apps.googleusercontent.com',
    iosBundleId: 'com.WalkMyPet.walkmypet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_sOOeYw3o482d0a7XXsXam9biGjq0AEU',
    appId: '1:885639863246:web:a9e011d9ae35d5a7cae99f',
    messagingSenderId: '885639863246',
    projectId: 'walkmypet-47e03',
    authDomain: 'walkmypet-47e03.firebaseapp.com',
    storageBucket: 'walkmypet-47e03.firebasestorage.app',
    measurementId: 'G-KR9VG2HVBG',
  );

}